### ISSUE TITLE
USER STORY: user can tell time for 5k

### ISSUE THREAD

**Issue by DionneMaguire** [DionneMaguire/my-first-Agile-project#5]
As a **user** I can **put up my time for 5k** so that **others can be encouraged to tell their time**

## Acceptance Criteria

- **Acceptance Criteria 1 :** user can leave comment about time it took to run 5k
- **Acceptance Criteria 2 :** user has option to tell route
- **Acceptance Criteria 3 :** user can leave comment about how they found it

## Tasks

- [ ] **Task 1** option to pick a route already known or to add a new route
- [ ] **Task 2** option to add time it took
- [ ] **Task 3** option to add any other comments
