### ISSUE TITLE
USER STORY: anonymous feedback as user I can choose to hide my identity

### ISSUE THREAD

**Issue by DionneMaguire** [DionneMaguire/my-first-Agile-project#6]
As a **user** I can **provide anonymous feedback as a user** so that **I can choose to hide my identity in the poll**

## Acceptance Criteria

- **The option should be provided as a checkbox**
- **the checkbox should be 'checked'  by default**
- **the option should appear next to submit button**
- **after submitting the default submission confirmation should be adjusted to include the user name**

## Tasks

- [ ] **update the view, poll design (HTML and CSS ) to include the checkbox and to show the name of the submitter**
- [ ] **Create a new field in the model to track username**
- [ ] **update the controller function**
- [ ] **update unit test scripts**
- [ ] **test functionality**
