### ISSUE TITLE
USER STORY: administrator can hide poll

### ISSUE THREAD

**Issue by DionneMaguire** [DionneMaguire/my-first-Agile-project#7]
As a **administrator** I can **pick an expiry date for poll** so that **I can hide the poll as administrator**

## Acceptance Criteria

- **poll should disappear at 11:59pm on target date**
- **Stay tuned for next poll if no poll active**
- **Administrators expiry date should be 3 days after current date**

## Tasks

- [ ] **update the admin view, poll design to pick expiry date**
- [ ] **update view to say stay tuned for next poll **
- [ ] **create javascript to validate the expiry date**
- [ ] **create job to check expiry dates on polls every day at 11:59 and hide them**
- [ ] ** update the controller function**
- [ ] **test functionality**
